[package]
name = "gcfeeder"
version = "0.1.0"
authors = ["Sirius902 <3645979-Sirius902@users.noreply.gitlab.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
iced = "0.1"
libc = "0.2"
once_cell = "1.4"
rusb = "0.6"
stoppable_thread = "0.2"
winapi = "0.3"
