[workspace]
members = ["crates/*"]
# TODO(Sirius902) Remove this once gcfeeder compiles with new API.
exclude = ["crates/gcfeeder"]
resolver = "2"

[workspace.package]
authors = ["Sirius902"]
description = "A ViGEm / evdev feeder for GameCube controllers using the GameCube Controller Adapter."
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Sirius902/gcfeeder"
version = "3.0.1"

[workspace.dependencies]
nalgebra = "0.33"
nusb = { version = "0.2", features = ["tokio"] }

[workspace.metadata.crane]
name = "workspace"
