[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
name = "gcfeederd"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console-subscriber = { version = "0.4", optional = true }
directories = "6"
gcfeeder-core = { path = "../gcfeeder-core" }
gcinput = { path = "../gcinput" }
nusb = "0.1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["rt"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = []
tokio-console = ["dep:console-subscriber"]
