[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
name = "gcinput"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
nalgebra = { workspace = true, optional = true }
serde = { version = "1", features = ["derive"] }

[features]
nalgebra = ["dep:nalgebra"]
