[package]
description.workspace = true
edition.workspace = true
name = "gcfeeder"
repository.workspace = true
version.workspace = true

[dependencies]
bincode = "1"
crossbeam = "0.8"
directories = "6"
egui = "0.31"
enum-iterator = "2"
nalgebra = "0.33"
once_cell = "1"
rayon = "1"
rusb = "0.9"
thiserror = "2"
toml = "0.8"
tray-icon = "0.19"
winit = "0.30"

[dependencies.gcinput]
path = "../gcinput"

[dependencies.panic-log]
path = "../panic-log"

[dependencies.gcfeeder-core]
path = "../gcfeeder-core"

[dependencies.eframe]
default-features = false
features = ["accesskit", "default_fonts", "wgpu"]
version = "0.31"

[dependencies.image]
default-features = false
features = ["png"]
version = "0.25"

[dependencies.log]
features = ["std"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.time]
features = ["macros", "formatting", "local-offset"]
version = "0.3"

[target.'cfg(windows)'.dependencies.windows]
features = ["Win32_UI_WindowsAndMessaging"]
version = "0.60"

[target.'cfg(target_os = "linux")'.dependencies.gtk]
default-features = false
features = []
version = "0.18"

[build-dependencies.git2]
default-features = false
features = []
optional = true
version = "0.20"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3"

[target.'cfg(windows)'.build-dependencies.image]
default-features = false
features = ["png", "ico"]
version = "0.25"

[features]
default = ["git-version"]
git-version = ["dep:git2"]
