name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Zig Build
      run: zig build -Dtarget=x86_64-windows -Dcpu=baseline
    - name: Upload gcfeeder
      uses: actions/upload-artifact@v2
      with:
        name: gcfeeder
        path: zig-out/bin
