name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Zig Build gcfeeder
      run: |
        zig build -Dtarget=x86_64-windows -Dcpu=baseline -Dfeeder-only
        mv zig-out feeder-out
    - name: Upload Feeder
      uses: actions/upload-artifact@v2
      with:
        name: gcfeeder
        path: feeder-out/bin
    - name: Zig Build gcviewer
      run: |
        zig build -Dtarget=x86_64-windows -Dcpu=baseline -Dviewer-only
        mv zig-out viewer-out
    - name: Upload Viewer
      uses: actions/upload-artifact@v2
      with:
        name: gcviewer
        path: viewer-out/bin
    - name: Upload Themes
      uses: actions/upload-artifact@v2
      with:
        name: theme
        path: theme
