name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Zig Build gcfeeder
      run: |
        cd feeder
        zig build -Dtarget=x86_64-windows -Dcpu=baseline
        cd ..
    - name: Upload Feeder
      uses: actions/upload-artifact@v2
      with:
        name: gcfeeder
        path: feeder/zig-out/bin
    - name: Zig Build gcviewer
      run: |
        cd viewer
        zig build -Dtarget=x86_64-windows -Dcpu=baseline
        cd ..
    - name: Upload Viewer
      uses: actions/upload-artifact@v2
      with:
        name: gcviewer
        path: viewer/zig-out/bin
    - name: Upload Themes
      uses: actions/upload-artifact@v2
      with:
        name: theme
        path: viewer/theme
