name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Zig Build
      run: zig build -Dtarget=x86_64-windows -Dcpu=baseline -Drelease-safe -Dversion="${{github.ref_name}}"
    - name: Compress Artifacts
      run: |
        7z a theme.zip ./theme/*
        7z a gcfeeder.zip ./zig-out/bin/gcfeeder.exe ./lib/libusb-1.0.dll
        7z a gcviewer.zip ./zig-out/bin/gcviewer.exe ./lib/glfw3.dll ./lib/libepoxy-0.dll
    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        files: |
          gcfeeder.zip
          gcviewer.zip
          theme.zip
