name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Zig Build gcfeeder
      run: |
        zig build -Dtarget=x86_64-windows -Dcpu=baseline -Drelease-safe -Dversion="${{github.ref_name}}" -Dfeeder-only
        rm zig-out/bin/*.pdb
        mv zig-out feeder-out
    - name: Zig Build gcviewer
      run: |
        zig build -Dtarget=x86_64-windows -Dcpu=baseline -Drelease-safe -Dversion="${{github.ref_name}}" -Dviewer-only
        rm zig-out/bin/*.pdb
        mv zig-out viewer-out
    - name: Compress Artifacts
      run: |
        7z a theme.zip ./theme/*
        7z a gcfeeder.zip ./feeder-out/bin/*
        7z a gcviewer.zip ./viewer-out/bin/*
    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: true
        files: |
          gcfeeder.zip
          gcviewer.zip
          theme.zip
